name: Validate schemas
on:
  push:
    tags-ignore:
      - '*'
    branches:
      - 'mainline'
  pull_request:
  workflow_dispatch:

jobs:
  validate-metadata:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Validate metadata
        run: yarn validate-metadatas
